language: java
# before_install:
# install IBM JDK7
# - curl -S -O http://watc4eb3.watson.ibm.com/ocdc/pool/IBM/i/ibm-j2sdk1.7/ibm-j2sdk1.7_1.7.0.9.30-0_amd64.deb
# - sudo dpkg -i ibm-j2sdk1.7_1.7.0.9.30-0_amd64.deb
# env:
#   global:
#   - JAVA_HOME=/usr/lib/j2sdk1.7-ibm
#   - PATH=${PATH}:${JAVA_HOME}/bin
# sudo: false
env:
  global:
    - OCTOKIT_API_ENDPOINT: https://github.ibm.com/api/v3/
jdk:
  - oraclejdk8
  - oraclejdk7
  - openjdk6
script: true
deploy:
  provider: releases
  api-key:
    secure: X5AyqEZXaEvlpoKl48duDT3Kb35wvtFoIcPQ/XMe3KB61YVFCs5j0itgy5vEcsrpxDEtYQe0wjvDr3/U45Ro5ef+D90X5fvQbFA/Tq7hkRBmQrfZzABVXPl6THlIVYIngPX3uW3N8ize9AUARiTIb/ihl4J3c3FlCGG9+1qq48s=
  file:
    - target/jaql-0.1.jar
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
    repo: infosec/jdbc-driver
    jdk: oraclejdk8
